name: analyze service

on:
  workflow_dispatch:

jobs:
  analyze:
    name: analyze code
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.5.x'
          
      - name: Build with dotnet
        run: dotnet build --configuration Release
        
      - name: install and run cyclonedx
        run: |
          dotnet tool install -g cyclonedx
          dotnet CycloneDX ./WebGoat.NET.sln --out ./ -gt ${{ secrets.CYCLONE_GITHUB_TOKEN }} -gu sfr@acies.dk

      - name: run semgrep
        run: |
          python3 -m pip install semgrep
          semgrep scan --config=auto --json -o semgrep.json

      - name: build artifacts
        run: |
          mkdir output
          sed -i '1s/^\xEF\xBB\xBF//' bom.xml
          cp bom.xml output/bom.xml
          cp semgrep.json output/semgrep.json

      - name: upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: output
