name: analyze service

on:
  workflow_dispatch:

jobs:
  analyze:
    name: analyze code
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3

      # - name: Add msbuild to PATH
      #   uses: microsoft/setup-msbuild@v1.1

      # - name: Restore NuGet Packages
      #   run: nuget restore WebGoat.NET.sln

      # - name: Build and Publish Web App
      #   run: msbuild WebGoat.NET.sln /p:Configuration=Release

      - name: run semgrep
        run: |
          python3 -m pip install semgrep
          semgrep scan --config="p/default" --json -o semgrep.json

      - name: build artifacts
        run: |
          mkdir output
          cp semgrep.json output/semgrep.json

      - name: upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: output
