name: analyze service

on:
  workflow_dispatch:

jobs:
  analyze:
    name: analyze code
    runs-on: windows-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
        
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
          
      - name: Restore NuGet Packages
        run: nuget restore WebGoat.NET.sln
 
      - name: Build and Publish Web App
        run: msbuild WebGoat.NET.sln /p:Configuration=Release

      - name: run semgrep
        run: |
          python3 -m pip install semgrep
          semgrep scan --config=auto --json -o semgrep.json

      - name: build artifacts
        run: |
          mkdir output
          sed -i '1s/^\xEF\xBB\xBF//' bom.xml
          cp bom.xml output/bom.xml
          cp semgrep.json output/semgrep.json

      - name: upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: output
